Investigating why libav fails on android with undefined reference to symbol x264_levels
Outcome of the investigation:

The reason is that if I link statically, I also need to manually
link to all recursive sub-dependencies. Which is currently
not feasible.